# Generated by Django 5.1.5 on 2025-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_alter_incidents_incidenttype_alter_incidents_score_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NGO',
            new_name='MunicipalCorporation',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='NGO_station',
            new_name='municipal_corporation',
        ),
        migrations.AlterField(
            model_name='incidents',
            name='incidentType',
            field=models.CharField(choices=[('Pothole/Road Damage', 'Pothole/Road Damage'), ('Water Pipe Burst', 'Water Pipe Burst'), ('Overflowing Trash Bins', 'Overflowing Trash Bins'), ('Illegal Dumping', 'Illegal Dumping'), ('Domestic Violence', 'Domestic Violence'), ('Child Abuse', 'Child Abuse'), ('Sexual Harassment', 'Sexual Harassment'), ('Stalking', 'Stalking'), ('Human Trafficking', 'Human Trafficking'), ('Fire', 'Fire'), ('Theft', 'Theft'), ('Accident', 'Accident'), ('Injury', 'Injury'), ('Missing Persons', 'Missing Persons'), ('Natural Disaster', 'Natural Disaster'), ('Medical Emergency', 'Medical Emergency'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
