# Generated by Django 5.1.5 on 2025-09-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_rename_ngo_municipalcorporation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='municipal_corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.municipalcorporation'),
        ),
    ]
